"""Generate explicit guest-ABI wrappers for reviewed native Xbox kernel services.

The whitelist is intentional. Callbacks, graphics ownership, and SEH are not
made native merely because the CPUs match; unsupported imports stop by name.
"""
import re,json
from pathlib import Path
root=Path(__file__).resolve().parent.parent
imports=json.loads((root/'analysis/default_analysis.json').read_text())['kernel_imports']
header=Path('C:/nxdk/lib/xboxkrnl/xboxkrnl.h').read_text()
allowed=set('''NtClose NtQueryVolumeInformationFile NtOpenFile RtlInitAnsiString
KeConnectInterrupt KeDisconnectInterrupt
IoCreateSymbolicLink IoDeleteSymbolicLink MmPersistContiguousMemory
AvGetSavedDataAddress AvSetSavedDataAddress AvSendTVEncoderOption AvSetDisplayMode
HalReadWritePCISpace HalGetInterruptVector MmClaimGpuInstanceMemory
MmLockUnlockBufferPages MmLockUnlockPhysicalPage KeSaveFloatingPointState KeRestoreFloatingPointState
KeInitializeTimerEx KeSetTimer KeInsertQueueDpc KeRemoveQueueDpc KeCancelTimer
NtWriteFile NtReadFile NtQuerySymbolicLinkObject NtOpenSymbolicLinkObject
RtlNtStatusToDosError NtFsControlFile NtSetInformationFile KeQuerySystemTime
NtCreateFile NtQueryFullAttributesFile NtQueryDirectoryFile RtlAnsiStringToUnicodeString
RtlUnicodeStringToAnsiString NtDuplicateObject NtWaitForSingleObject NtQueryInformationFile
NtFlushBuffersFile NtDeviceIoControlFile ObfDereferenceObject ObReferenceObjectByHandle
MmFreeSystemMemory MmAllocateSystemMemory XcSHAUpdate XcSHAInit XcSHAFinal
MmAllocateContiguousMemory MmFreeContiguousMemory ExQueryNonVolatileSetting
MmAllocateContiguousMemoryEx MmQueryAllocationSize MmSetAddressProtect MmQueryAddressProtect
RtlLeaveCriticalSection RtlEnterCriticalSection KeSetBasePriorityThread KeQueryBasePriorityThread
KeSetDisableBoostThread NtSuspendThread NtResumeThread NtYieldExecution
NtCreateEvent NtSetEvent NtClearEvent NtCreateSemaphore NtReleaseSemaphore NtCreateMutant
NtReleaseMutant NtWaitForSingleObjectEx NtWaitForMultipleObjectsEx KeDelayExecutionThread
NtFreeVirtualMemory NtAllocateVirtualMemory RtlCompareMemoryUlong RtlInitializeCriticalSection
NtQueryVirtualMemory RtlEqualString KeSetEvent KeWaitForSingleObject XcHMAC
KeStallExecutionProcessor ExQueryPoolBlockSize ExAllocatePoolWithTag ExFreePool
MmGetPhysicalAddress MmQueryStatistics RtlTimeToTimeFields RtlTimeFieldsToTime
HalIsResetOrShutdownPending'''.split())
data=set('HalDiskCachePartitionCount IoFileObjectType XboxHDKey XboxSignatureKey XboxAlternateSignatureKeys LaunchDataPage PsThreadObjectType ExEventObjectType HalBootSMCVideoMode XboxHardwareInfo XeImageFileName XboxKrnlVersion IdexChannelObject KeTickCount'.split())
manual={'PsCreateSystemThreadEx':'bridge_create_thread','PsTerminateSystemThread':'bridge_exit_thread'}
manual['HalRegisterShutdownNotification']='bridge_shutdown_notification'
manual.update({'XeLoadSection':'bridge_load_section','XeUnloadSection':'bridge_unload_section'})
manual['KeInitializeDpc']='bridge_initialize_dpc'
manual.update({'KfLowerIrql':'bridge_lower_irql','KfRaiseIrql':'bridge_raise_irql','KeRaiseIrqlToDpcLevel':'bridge_raise_dpc'})
manual.update({'KeInitializeInterrupt':'bridge_initialize_interrupt','KeSynchronizeExecution':'bridge_synchronize'})
manual.update({'KeSaveFloatingPointState':'bridge_save_float','KeRestoreFloatingPointState':'bridge_restore_float'})
lines=['/* Generated by nxdk/generate_kernel.py; do not edit by hand. */']
entries=[]; report=[]
for item in imports:
    name=item['name'];ordinal=item['ordinal'];fn='bridge_'+name
    if name in data:
        entries.append(f'case {ordinal}: return (uint32_t)(uintptr_t)&{name};')
        report.append({'name':name,'kind':'native-data'});continue
    if name in manual:
        report.append({'name':name,'kind':'manual'});continue
    match=re.search(r'XBAPI\s+(\w+)\s+(NTAPI|FASTCALL|CDECL)\s+'+name+r'\s*\((.*?)\)\s*;',header,re.S)
    if name not in allowed or not match:
        lines.append(f'static void {fn}(void) {{ nxdk_port_fail("kernel: {name}",__FILE__,__LINE__); }}')
        report.append({'name':name,'kind':'unsupported'});continue
    result,conv,parameters=match.groups()
    parameters=re.sub(r'/\*.*?\*/','',parameters,flags=re.S).strip()
    params=[] if parameters in ('','void','VOID') else parameters.split(',')
    args=[];index=1;body=[];io_apc=False
    for p in params:
        p=re.sub(r'\b(IN|OUT|OPTIONAL|CONST)\b','',p).strip()
        p=re.sub(r'\b(\w+)\[\]$',r'*\1',p)
        m=re.match(r'(.+?[\s*])(\w+)$',p)
        if not m: raise SystemExit((name,p))
        t,n=m.groups();t=t.strip()
        if t in ('LARGE_INTEGER','ULARGE_INTEGER','ULONGLONG','LONGLONG'):
            expr=f'ARG64({index})';index+=2
            if t in ('LARGE_INTEGER','ULARGE_INTEGER'): expr=f'({t}){{.QuadPart={expr}}}'
            else:expr=f'({t}){expr}'
        else:
            v=(f'g_ecx' if index==1 else 'g_edx') if conv=='FASTCALL' and index<=2 else f'ARG({index if conv!="FASTCALL" else index-2})'
            expr=f'({t})(uintptr_t){v}';index+=1
            if t in ('PKTHREAD','PRKTHREAD','PETHREAD'):expr=f'({t})port_native_thread({v})'
            if t=='PIO_APC_ROUTINE':
                if v!='ARG(3)':raise SystemExit('Unexpected I/O APC argument layout: '+name)
                io_apc=True
                expr='apc ? io_apc_callback : NULL'
            elif io_apc and n=='ApcContext':expr='apc ? (PVOID)apc : (PVOID)(uintptr_t)ARG(4)'
            elif 'ROUTINE' in t:body.append(f'if({v})nxdk_port_fail("{name}: guest callback requires trampoline",__FILE__,__LINE__);')
        args.append(expr)
    call=f'{name}('+','.join(args)+')'
    if result in ('VOID','void'):body.append(call+';')
    elif result in ('ULONGLONG','LONGLONG'):body.append(f'uint64_t result={call};g_eax=(uint32_t)result;g_edx=(uint32_t)(result>>32);')
    else:body.append(f'g_eax=(uint32_t)(uintptr_t){call};')
    if name in ('MmAllocateContiguousMemory','MmAllocateContiguousMemoryEx','MmAllocateSystemMemory','ExAllocatePoolWithTag'):
        body.append(f'if(!g_eax)port_log("ALLOC FAILED {name} bytes=%lu\\n",(unsigned long)ARG(1));')
    if name=='NtAllocateVirtualMemory':body.append('if((int32_t)g_eax<0)port_log("VM FAILED status=%08lx size=%lu\\n",(unsigned long)g_eax,(unsigned long)MEM32(ARG(3)));')
    cleanup=(index-1)*4 if conv=='NTAPI' else max(0,index-3)*4 if conv=='FASTCALL' else 0
    if io_apc:
        body.insert(0,f'IoApcBridge *apc=ARG(3)?io_apc_begin(ARG(3),ARG(4)):NULL;if(ARG(3)&&!apc){{g_eax=0xc000009au;g_esp+={cleanup+4};return;}}')
        body.append('if(apc&&(int32_t)g_eax<0)InterlockedExchange(&apc->used,0);')
    body.append(f'g_esp+={cleanup+4};')
    lines.append('static void '+fn+'(void) { '+''.join(body)+' }')
    report.append({'name':name,'kind':'native-wrapper','argument_words':index-1,'convention':conv,**({'callback':'thread-affine I/O APC bridge'} if io_apc else {})})
lines+=['static uint32_t native_data(unsigned ordinal) {switch(ordinal){',*entries,'default:return 0;}}',
        'static recomp_func_t native_function(unsigned ordinal) {switch(ordinal){']
for item in imports:
    name=item['name']
    if name not in data:lines.append(f'case {item["ordinal"]}:return {manual.get(name,"bridge_"+name)};')
lines+=['default:return NULL;}}']
(root/'nxdk/native_imports.inc').write_text('\n'.join(lines)+'\n')
(root/'nxdk/kernel-coverage.json').write_text(json.dumps(report,indent=2)+'\n')
print({k:sum(x['kind']==k for x in report) for k in sorted(set(x['kind'] for x in report))})
