"""Generate weighted-position expectations by executing the original XML2 XBE.

Usage: python scripts/xml2-skinning-oracle.py XBE --out VECTOR_DIRECTORY
Requires the recovered inspect_xbe reader and local Unicorn installation.
"""
from pathlib import Path
import sys,struct,random,argparse
from unicorn import Uc,UC_ARCH_X86,UC_MODE_32
from unicorn.x86_const import *
root=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('xbe',type=Path)
parser.add_argument('--out',type=Path,required=True)
args=parser.parse_args()
sys.path.insert(0,str(root/'work/xml2-integration/recovery/xml2-pc'))
from inspect_xbe import Xbe
x=Xbe(str(args.xbe));u=Uc(UC_ARCH_X86,UC_MODE_32);u.mem_map(0,0x2000000)
for s in x.sections:u.mem_write(s['va'],x.data[s['raw']:s['raw']+s['raw_size']])
assert x.data[x.va_offset(0x2b5a5b):x.va_offset(0x2b5a5b)+2]==bytes.fromhex('e2c0')
r=random.Random(2718);rows=[]
for count in (1,4,9):
 for influences in (1,2,3,4):
  for stride in (12,32):
   positions=[r.randrange(-80,81)/4 for _ in range(36)]
   weights=[0.0]*36;ids=[0]*36
   for v in range(count):
    for k in range(influences):
     ids[v*influences+k]=(v+k)%4
     weights[v*influences+k]=1.0 if influences==1 else (0.0 if k==0 else 1.0/(influences-1))
   matrices=[]
   for b in range(4):matrices += [1+b*.25,0,0,0, 0,1+b*.5,0,0, 0,0,1+b*.125,0, b*10,b*-3,b*7,1]
   base=0x1100000;sp=0x1001000;ret=0x1000000
   for off,values in ((0,positions),(0x100,weights),(0x300,matrices)):u.mem_write(base+off,struct.pack('<%df'%len(values),*values))
   u.mem_write(base+0x200,bytes(ids));u.mem_write(base+0x500,bytes([0xa5])*288)
   u.mem_write(sp,struct.pack('<9I',ret,base,count,base+0x100,base+0x200,influences,base+0x300,base+0x500,stride))
   for reg,val in ((UC_X86_REG_ESP,sp),(UC_X86_REG_EBP,0x123400),(UC_X86_REG_EBX,0x123456),(UC_X86_REG_ESI,0x234567),(UC_X86_REG_EDI,0x345678),(UC_X86_REG_EFLAGS,2)):u.reg_write(reg,val)
   u.emu_start(0x2b59f0,ret,count=100000)
   assert u.reg_read(UC_X86_REG_EIP)==ret and u.reg_read(UC_X86_REG_ESP)==sp+4
   rows.append((count,influences,stride,positions,weights,matrices,ids,list(u.mem_read(base+0x500,288))))
def fs(v):return '{'+','.join(float(x).hex()+'f' for x in v)+'}'
def bs(v):return '{'+','.join(str(x) for x in v)+'}'
args.out.mkdir(parents=True,exist_ok=True)
out=args.out/'skin-vectors.h'
out.write_text('/* Original XML2 x86 2B59F0 oracle; generated by skin-oracle.py. */\nstatic const struct SkinVector {unsigned count,influences,stride;float positions[36],weights[36],matrices[64];unsigned char ids[36],expected[288];} skin_vectors[]={\n'+''.join('{%d,%d,%d,%s,%s,%s,%s,%s},\n'%(n,k,s,fs(p),fs(w),fs(m),bs(ids),bs(e)) for n,k,s,p,w,m,ids,e in rows)+'};\n')
print('PASS original x86 skinning oracle:',len(rows),'cases; 1-4 influences, zero-first weights, 1/4/9 vertices, 12/32-byte stride')
